# Generated by Django 4.0 on 2021-12-21 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('date', models.DateTimeField(auto_now=True)),
                ('machine_no', models.IntegerField(primary_key=True, serialize=False)),
                ('machine_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='McDailyRecordingArea',
            fields=[
                ('date', models.DateTimeField(default=datetime.date(2021, 12, 21), primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='McRecordingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(choices=[('Nose', 'Nose wire funnel'), ('feeder', 'Material feeder aligner'), ('welding', 'Blanking welding'), ('Other', 'Other')], default='Root Cause', max_length=300)),
                ('action_taken', models.CharField(choices=[('1.', 'Align nose wire funnel'), ('aligner', 'Material aligner'), ('Blanking', 'Blanking welding'), ('Other', 'Other')], default='Action Taken', max_length=300)),
                ('remarks', models.CharField(default='Remarks', max_length=300, null=True)),
                ('total_down_time', models.FloatField(default=None, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
            options={
                'ordering': ['machine', 'total_down_time', 'action_taken', 'root_cause'],
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
