# Generated by Django 4.0 on 2021-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_machine_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_no',
            field=models.IntegerField(default=1),
        ),
    ]
