# Generated by Django 4.0 on 2021-12-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mcdailyrecordingarea_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcrecordingarea',
            name='dalydate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mcdailyrecordingarea'),
        ),
    ]
