# Generated by Django 4.0 on 2021-12-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_machine_machine_status_alter_machine_machine_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
