# Generated by Django 4.0 on 2021-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mcrecordingarea_dalydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcrecordingarea',
            name='total_down_time',
            field=models.FloatField(default=None),
        ),
    ]
