# Generated by Django 4.0 on 2021-12-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mcrecordingarea_total_down_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcdailyrecordingarea',
            old_name='date',
            new_name='dailydate',
        ),
    ]
