# Generated by Django 4.0 on 2021-12-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_machine_machine_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McRecordingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=300)),
                ('total_down_time_hour', models.IntegerField()),
                ('total_down_time_minute', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
            options={
                'ordering': ['action_taken'],
            },
        ),
    ]
