# Generated by Django 4.0 on 2021-12-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_mcdailyrecordingarea_dailydate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcrecordingarea',
            options={},
        ),
    ]
