# Generated by Django 4.0 on 2021-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mcrecordingarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='id',
        ),
        migrations.AddField(
            model_name='mcrecordingarea',
            name='rootcause',
            field=models.CharField(default='Root Cause:', max_length=300),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcrecordingarea',
            name='action_taken',
            field=models.CharField(default='Action Taken:', max_length=300),
        ),
    ]
