# Generated by Django 4.0 on 2021-12-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mcrecordingarea_rootcause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcrecordingarea',
            name='remarks',
            field=models.CharField(default='Remarks', max_length=300),
        ),
    ]
