# Generated by Django 4.0 on 2021-12-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_mcrecordingarea_total_down_time_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcrecordingarea',
            name='total_down_time',
            field=models.DateTimeField(null=True),
        ),
    ]
