# Generated by Django 4.0 on 2021-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mcrecordingarea_total_down_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcrecordingarea',
            name='total_down_time',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
