# Generated by Django 4.0 on 2021-12-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_mcrecordingarea_action_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcrecordingarea',
            name='machine',
        ),
    ]
