# Generated by Django 4.0 on 2021-12-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_mcrecordingarea_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcrecordingarea',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.machine'),
            preserve_default=False,
        ),
    ]
