# Generated by Django 4.0 on 2021-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_mcrecordingarea_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcrecordingarea',
            name='action_taken',
            field=models.CharField(choices=[('1.', 'Align nose wire funnel'), ('aligner', 'Material aligner'), ('Blanking', 'Blanking welding'), ('Other', 'Other')], default='Action Taken', max_length=300),
        ),
        migrations.AlterField(
            model_name='mcrecordingarea',
            name='root_cause',
            field=models.CharField(choices=[('Nose', 'Nose wire funnel'), ('feeder', 'Material feeder aligner'), ('welding', 'Blanking welding'), ('Other', 'Other')], default='Root Cause', max_length=300),
        ),
    ]
