# Generated by Django 4.0 on 2021-12-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_mcrecordingarea_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcrecordingarea',
            options={'ordering': ['machine', 'total_down_time', 'action_taken', 'root_cause']},
        ),
    ]
